"""empty message

Revision ID: 9689f5131b70
Revises: 256a30ba3d0e
Create Date: 2021-07-27 15:51:08.176236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9689f5131b70'
down_revision = '256a30ba3d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('user_desc', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_desc')
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###
